# Generated by Django 6.1.1 on 2026-09-10 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('INFRASTRUCTURE', 'Infrastructure'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('AGRICULTURE', 'Agriculture'), ('OTHERS', 'Others')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened')], default='PENDING', max_length=20)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='accounts.village')),
            ],
            options={
                'db_table': 'grievances',
                'ordering': ['-created_at'],
            },
        ),
    ]
