# Generated by Django 5.2.17 on 2026-10-01 20:06

import django.db.models.deletion
import grievances.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('grievances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=255, verbose_name='Problem kya thi')),
                ('work_quality', models.CharField(choices=[('BAHUT_ACHHA', 'Bahut Badhiya (Excellent)'), ('ACHHA', 'Achha Kaam Hua (Good)'), ('THEEK', 'Theek-thaak (Satisfactory)'), ('ASANTUSHT', 'Asantusht (Unsatisfactory)')], default='ACHHA', max_length=50, verbose_name='Kaisa kaam hua')),
                ('rating', models.IntegerField(default=5)),
                ('comments', models.TextField(validators=[grievances.models.validate_max_50_words], verbose_name='Feedback (Max 50 Words)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='grievances.grievance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.village')),
            ],
            options={
                'db_table': 'grievance_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
