# Generated by Django 5.2.17 on 2026-10-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VILLAGER', 'Villager'), ('FARMER', 'Farmer'), ('PANCHAYAT_ADMIN', 'Panchayat Admin')], default='VILLAGER', max_length=30),
        ),
    ]
