# Generated by Django 5.2.17 on 2026-10-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agritech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoilHealthCard',
        ),
    ]
